### ISSUE TITLE
Author Profile - Use the Name from the Author Profile Globally

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#19]
The author profile is intended to be the canonical, or exact spelling/formatting of both the Author Name and the Author Bio/Profile. This allows us to update both the name and the Bio once and have it cascade to all Storybook Projects keyed to that Profile.

Currently, the name in the profile is not being used in all places that the name appears. It is only being used in the profile box.

We need the author profile `Name` sting to be used anywhere the Author Name appears in the Storybook Presentation. When the profile cannot be loaded, fall back to the string in the `sbplus.xml`.

**Comment by Lin87** [comment]
If using the name from the author profile, assuming that you are referring to the JSON file, SB+ would have to request and parse the JSON file for a short string that is only used in two places: splash screen and the black title bar. The splash screen would not be displayed again during a viewing "session." So, it will be only be displayed in the title bar.

Currently, I had it load only when user requested it (to see the author profile) because some users may not open the author profile under menu at all during the "session." It would be one less item to request from the server. Instead of always on demand, it would be load on demand.

Is there a reason why the name in XML would be different from the name in JSON file? To me, this should be like a best practice to have the name in the XML and JSON to be the same. Plus, this provides the flexibility to display different "information" at two places for some situations instead of being determined by the information in a centralized JSON file, which may not even exist.

Thoughts? @patrick-wirth and @mwolfensteinuwex if you have the time to spare.

**Comment by Lin87** [comment]
Implemented in version 3.1.

**Comment by owlboy** [comment]
This regressed. And I have an example of a use case that I was anticipating.

**Example presentation:**
https://media.uwex.edu/content/abt/abt715/abt715_electrochemistry.sbproj/

**Name:**
/httpdocs/content/media/player_support/author/francismann.jpg
/httpdocs/content/media/player_support/author/francismann.json

**Desired Name:**
Francis "Frannie" Mann

**Comment by Lin87** [comment]
Fixed. The author's name on splash screen and on the black bar is now retrieved from the JSON file. Default to the name in XML if no JSON is available. Please confirm the fix. Close the issue if the fix satisfies the request. Thank you.
