### ISSUE TITLE
Make Quiz correct attributes case insensitive.

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#47]
Hello,

Just a minor tweak request if it's not a big deal to implement:

When writing quiz question XML it would be nice if the correct="Yes" attribute would be case insensitive so that "Yes" works along with "yes".

If this is acceptable, then please also apply the change to any other attributes where case insensitivity makes sense.

**Comment by Lin87** [comment]
This issue is more related to SB+ 3.0. In 3.1, case (or any value; i.e., "yes", "no", etc.) does not really matter as long as it is not undefined. It is used to flag the correct choice(s), and the value inside the flagged `choice` tag is actually sanitized and compared to the student's selection. In short, `correct` attribute can hold any string in upper or lower case.
