### ISSUE TITLE
Bulleted Lists in Author Profiles

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#74]
I am having trouble getting bullets in lists to display in author profiles. When I edit things in the inspector in Safari to add the CSS to make them display again they are aligned poorly. Please check that ordered lists work too.

**Comment by Lin87** [comment]
There is nothing wrong with the unordered and ordered list in the author profile. No custom CSS was applied. They were displaying out of alignment because of the float property on the image. There is no other way to float an image without using float the property. To resolve the displaying issue, the image is now floated to the right. There are hacks but they are for collection of images and not really for wrapping text to image.
